### Bayes Theorem for medical diagnosis Problem 

In [1]:

def bayes_theorem(p_disease, p_positive_given_disease, p_negative_given_no_disease):
    p_no_disease = 1 - p_disease
    p_positive_given_no_disease = 1 - p_negative_given_no_disease
    
    p_positive = (p_positive_given_disease * p_disease) + (p_positive_given_no_disease * p_no_disease)
    
    p_disease_given_positive = (p_positive_given_disease * p_disease) / p_positive
    
    return p_disease_given_positive

p_disease = 0.001
p_positive_given_disease = 0.99
p_negative_given_no_disease = 0.95

result = bayes_theorem(p_disease, p_positive_given_disease, p_negative_given_no_disease)
print(f"Probability of having the disease given a positive test result: {result:.4f}")

Probability of having the disease given a positive test result: 0.0194


#### Eigen Values and Eigen Vectors

In [2]:

import numpy as np

A = np.array([[4, -2],
              [1, 1]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)


Eigenvalues:
[3. 2.]
Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


#### Diterminant And inverse of a matrix if possible 

In [3]:
B = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

det = np.linalg.det(B)
print(f"Determinant: {det:.4f}")

if det != 0:
    inverse = np.linalg.inv(B)
    print("Inverse:")
    print(inverse)
else:
    print("The matrix is singular and does not have an inverse.")


Determinant: 1.0000
Inverse:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


#### Properties and Applications of the Normal Distribution and Calculate Probabilities
#### The Normal distribution is characterized by its mean (μ) and standard deviation (σ). It has several important properties:

##### Symmetric about the mean
##### Mean, median, and mode are equal
##### The area under the curve represents probabilities and the total area is 1

In [4]:
from scipy.stats import norm

# Parameters for the Normal distribution
mu = 0
sigma = 1

# Calculate the probability of a value less than or equal to x
x = 1.96
probability = norm.cdf(x, mu, sigma)
print(f"Probability of a value less than or equal to {x}: {probability:.4f}")

# Calculate the probability of a value within a range
x1 = -1.96
x2 = 1.96
probability_range = norm.cdf(x2, mu, sigma) - norm.cdf(x1, mu, sigma)
print(f"Probability of a value between {x1} and {x2}: {probability_range:.4f}")


Probability of a value less than or equal to 1.96: 0.9750
Probability of a value between -1.96 and 1.96: 0.9500
